### PR TITLE
JsonSchema is now properly either a schema or boolean

### LINKED ISSUE #34: Json Schemas are either a schema or boolean
```json
    "type": ["object", "boolean"],
```

currently, when we attempt to transpile the fhir schema, we get the following error.

```
io.carrera.jsontoavroschema.ParserError: additionalProperties
```

There are a number of places in the fhir schema that uses this.

```json
"additionalProperties": false
```

I'm not entirely certain how this should transpile yet.

>    The value of "additionalProperties" MUST be a valid JSON Schema.
> 
>    This keyword determines how child instances validate for objects, and
>    does not directly validate the immediate instance itself.
> 
>    Validation with "additionalProperties" applies only to the child
>    values of instance names that do not match any names in "properties",
>    and do not match any regular expression in "patternProperties".
> 
>    For all such properties, validation succeeds if the child instance
>    validates against the "additionalProperties" schema.
> 
>    Omitting this keyword has the same behavior as an empty schema.

https://tools.ietf.org/html/draft-wright-json-schema-validation-01#section-6.20

> 4.4.  JSON Schema documents
> 
>    A JSON Schema document, or simply a schema, is a JSON document used
>    to describe an instance.  A schema is itself interpreted as an
>    instance.  A JSON Schema MUST be an object or a boolean.
> 
>    Boolean values are equivalent to the following behaviors:
> 
>    true  Always passes validation, as if the empty schema {}
>    false  Always fails validation, as if the schema { "not":{} }

If `additionalProperties: false` means no child elements should be valid, what does that mean when we're transpiling?

### PR DESCRIPTION
**Pull request by rubberduck203**
Closes #34 

FHIR schema successfully transpiles, but the resulting AVRO schema isn't quite valid.

### CODE REVIEW

File: src/main/scala/IdNormalizer.scala [hunk 1]
```diff
@@ -1,45 +1,57 @@
 package io.carrera.jsontoavroschema
 
+import Thing.JSchema
```
Comment (rubberduck203) [inline src/main/scala/IdNormalizer.scala:3]: Needs a better name than `Thing` ducky.

File: src/main/scala/IdNormalizer.scala [hunk 2]
```diff
@@ -1,45 +1,57 @@
...
 
 object IdNormalizer {
-  def normalizeIds(root: JsonSchema): Either[ResolutionError, JsonSchema] =
-    for {
-      baseUri <- root.id.toRight(ResolutionError("$id must be specified in root schema"))
-      resolved <- normalizeIds(root, baseUri)
-    } yield resolved
+  def normalizeIds(root: JSchema): Either[ResolutionError, JSchema] = {
+    root match {
+      case Left(bool) => Right(Left(bool))
```
Comment (rubberduck203) [inline src/main/scala/IdNormalizer.scala:10]: We're just propogating the `Left`, wrapped in a `Right`.
Is there a more elegant way to do this?

File: src/main/scala/JsonSchemaParser.scala [hunk 3]
```diff
@@ -20,83 +22,92 @@ object JsonSchemaParser {
...
+              enum,
+              format,
+              allOf,
+              anyOf,
+              oneOf,
+              not,
+            )
+          )
+        }
+      //FIXME: inexhaustive match
```
Comment (rubberduck203) [inline src/main/scala/JsonSchemaParser.scala:108]: This needs fixed before merging

File: src/main/scala/JsonSchemaParser.scala [hunk 4]
```diff
@@ -234,11 +245,16 @@ object JsonSchemaParser {
...
-      schema <- parseSubSchema(obj)
-    } yield schema
+  private def parseSchema(value: ujson.Value, errMsg: String) = {
+    value match {
+      case ujson.Bool(v) => Right(Left(v))
+      case ujson.Obj(obj) =>
+        for {
+          schema <- parseSubSchema(obj)
+        } yield schema
+      case _ => Left(ParserError(errMsg))
```
Comment (rubberduck203) [inline src/main/scala/JsonSchemaParser.scala:255]: "Expected Bool or Obj: $errMsg" or something like that would be a better error message

File: src/main/scala/Transpiler.scala [hunk 5]
```diff
@@ -64,129 +75,166 @@ object Transpiler {
...
-        else {
-          val subCtx = Context(prop, None, ctx.symbols)
-          for {
-            record <- transpile(prop.id.map(toName).getOrElse(name), subCtx)
-          } yield (record, None)
-        }
-    } yield AvroField(name, prop.desc, typeAndDefault._1, typeAndDefault._2, None /* TODO: order */)
+  private def resolveField(name: String, prop: JSchema, ctx: Context) = {
+    prop match {
+      case Left(_) => Left(TranspileError(s"Unexpected boolean schema at $name"))
```
Comment (rubberduck203) [inline src/main/scala/Transpiler.scala:133]: `prop.left.map`?

File: src/main/scala/Transpiler.scala [hunk 6]
```diff
@@ -64,129 +75,166 @@ object Transpiler {
...
-          optionalList(schema.`enum`)
-            .map(resolveEnum(propName, _))
-        } orElse {
-          optionalList(schema.oneOf)
-            .map(resolveOneOf(propName, _, ctx))
-        } getOrElse {
+    schema match {
+      case Left(bool) =>
+        if (bool)
           Right(AvroBytes)
```
Comment (rubberduck203) [inline src/main/scala/Transpiler.scala:171]: Deserves a comment that a `true` schema allows any thing at all.

File: src/main/scala/IdNormalizer.scala (hunk 2 above)
Comment (rubberduck203) [reply src/main/scala/IdNormalizer.scala:10]: It's fine. I don't like the alternatives I played with.

File: src/main/scala/Transpiler.scala (hunk 5 above)
Comment (rubberduck203) [reply src/main/scala/Transpiler.scala:133]: You can do this

```scala
    prop
      .left
        .map(_ => TranspileError(s"Unexpected boolean schema at $name"))
        .flatMap { schema => //...
```

But I honestly think it's less clear.
